// <auto-generated />
namespace WFM.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Audit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Audit));
        
        string IMigrationMetadata.Id
        {
            get { return "202003090303127_Audit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
