//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataAudit
    {
        public int Id { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Entity { get; set; }
        public string OldData { get; set; }
        public string NewData { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
