//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonHistory
    {
        public int Id { get; set; }
        public Nullable<int> TitleId { get; set; }
        public string Name { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string ContactNo { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public Nullable<int> SubOrganizationId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
    
        public virtual Designation Designation { get; set; }
        public virtual Division Division { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual SubOrganization SubOrganization { get; set; }
        public virtual Title Title { get; set; }
    }
}
