//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonRelationshipDetail
    {
        public int Id { get; set; }
        public Nullable<int> PersonRelationshipId { get; set; }
        public Nullable<int> RelationshipTypeId { get; set; }
        public Nullable<int> PersonId { get; set; }
    
        public virtual PersonRelationship PersonRelationship { get; set; }
        public virtual RelationshipType RelationshipType { get; set; }
    }
}
