//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;

    public partial class WFM_BidNoBidDecision
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> StrategicFit { get; set; }
        public Nullable<int> WinProbability { get; set; }
        public Nullable<int> TechCapability { get; set; }
        public Nullable<int> Resource { get; set; }
        public Nullable<int> Profitability { get; set; }
        public Nullable<int> ClientRelationship { get; set; }
        public Nullable<int> Risks { get; set; }
        public Nullable<int> Total { get; set; }
        public string Decision { get; set; }
        public string Notes { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
