//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFM_ProjectDocumentFieldValue
    {
        public int Id { get; set; }
        public int DocumentFieldId { get; set; }
        public string Value { get; set; }
        public int ProjectId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual WFM_DocumentField WFM_DocumentField { get; set; }
        public virtual WFM_Project WFM_Project { get; set; }
    }
}
