//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFM_Meeting
    {
        public int Id { get; set; }
        public Nullable<int> MeetingTypeId { get; set; }
        public string Location { get; set; }
        public string ExternalParticipants { get; set; }
        public string KPI { get; set; }
        public Nullable<bool> KPIAchieved { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> RelatedTaskId { get; set; }
    }
}
