//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFM_DocumentField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFM_DocumentField()
        {
            this.WFM_ProjectDocumentFieldValue = new HashSet<WFM_ProjectDocumentFieldValue>();
        }
    
        public int Id { get; set; }
        public int DocumentId { get; set; }
        public string FieldName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual WFM_Document WFM_Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFM_ProjectDocumentFieldValue> WFM_ProjectDocumentFieldValue { get; set; }
    }
}
