//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;

    public partial class WFM_GateControl
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<bool> QG1Bid { get; set; }
        public Nullable<bool> QG2Kickoff { get; set; }
        public Nullable<bool> QG3Fifty { get; set; }
        public Nullable<bool> QG4Ninety { get; set; }
        public Nullable<bool> QG5Approve { get; set; }
        public Nullable<bool> QG6Submit { get; set; }
        public Nullable<int> GatesDone { get; set; }
        public Nullable<int> PercentComplete { get; set; }
        public string CurrentStage { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
