//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFM_TaskTracker
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<int> MeetingTypeId { get; set; }
        public Nullable<System.DateTime> DateOfMeeting { get; set; }
        public string TaskDescription { get; set; }
        public string CurrentProgressNote { get; set; }
        public Nullable<bool> AddToAgenda { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<int> AuthorityId { get; set; }
        public Nullable<int> AssigneeId { get; set; }
        public Nullable<System.DateTime> DateOfAssignment { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> TakenNextDueDate { get; set; }
        public Nullable<int> EmailTo { get; set; }
        public string EmailSubject { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> TaskTypeId { get; set; }
        public Nullable<int> AddToAgendaMeetingId { get; set; }
        public Nullable<System.DateTime> ActuallyStartedDate { get; set; }
        public Nullable<System.DateTime> ActuallyCompletedDate { get; set; }
        public Nullable<int> TaskTrackerCategoryId { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<System.DateTime> ScheduleTime { get; set; }
        public string NoOfHrs { get; set; }
        public Nullable<int> MeetingId { get; set; }
    }
}
