//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;

    public partial class WFM_ProposalOutcome
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Outcome { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
        public string WinningConsultant { get; set; }
        public Nullable<int> TechnicalScore { get; set; }
        public Nullable<int> FinancialScore { get; set; }
        public Nullable<int> TotalScore { get; set; }
        public string ReasonForLoss { get; set; }
        public string LessonLearned { get; set; }
        public string FollowUpAction { get; set; }
        public string ActionOwner { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
