//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFM_Form8B
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> DateOfRequest { get; set; }
        public Nullable<int> ProjectSectorId { get; set; }
        public string DescriptionOfTheProject { get; set; }
        public Nullable<decimal> TotalProjectValue { get; set; }
        public string CompanyRepresentingCCC { get; set; }
        public string RoleToBePlayedByCCC { get; set; }
        public string NameOfSignatoryCCC { get; set; }
        public string DesignationOfSignatoryCCC { get; set; }
        public string OtherPartyName { get; set; }
        public string OtherPartyRegNo { get; set; }
        public string OtherPartyAddress { get; set; }
        public string OtherPartyEmail { get; set; }
        public string RoleToBePlayedByOtherParty { get; set; }
        public string NameOfSignatoryOtherParty { get; set; }
        public string DesignationOfSignatoryOtherParty { get; set; }
        public string OtherPartyName1 { get; set; }
        public string OtherPartyRegNo1 { get; set; }
        public string OtherPartyAddress1 { get; set; }
        public string OtherPartyEmail1 { get; set; }
        public string OtherPartyLegalDocument1 { get; set; }
        public string OtherPartyLegalDocument2 { get; set; }
        public string OtherPartyLegalDocument3 { get; set; }
        public string MethodOfRemunerationToCCC { get; set; }
        public string LegalFacilitation1 { get; set; }
        public string LegalFacilitation2 { get; set; }
        public string LegalFacilitation3 { get; set; }
        public string LegalFacilitation4 { get; set; }
        public string LegalFacilitation5 { get; set; }
        public string LegalFacilitation6 { get; set; }
        public string LegalFacilitation7 { get; set; }
        public string LegalFacilitation8 { get; set; }
        public string LegalFacilitation9 { get; set; }
        public string LegalFacilitation10 { get; set; }
        public string ValidityPeriodOfTheAgreement { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
    }
}
