//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFM_MarketingSourcingPartner
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int SourcingPartnerId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual WFM_SourcingPartner WFM_SourcingPartner { get; set; }
        public virtual WFM_Project WFM_Project { get; set; }
    }
}
