//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;

    public partial class WFM_ProjectHandover
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<bool> H1 { get; set; }
        public string H1Note { get; set; }
        public Nullable<bool> H2 { get; set; }
        public string H2Note { get; set; }
        public Nullable<bool> H3 { get; set; }
        public string H3Note { get; set; }
        public Nullable<bool> H4 { get; set; }
        public string H4Note { get; set; }
        public Nullable<bool> H5 { get; set; }
        public string H5Note { get; set; }
        public Nullable<bool> H6 { get; set; }
        public string H6Note { get; set; }
        public Nullable<bool> H7 { get; set; }
        public string H7Note { get; set; }
        public Nullable<bool> H8 { get; set; }
        public string H8Note { get; set; }
        public Nullable<int> ItemsDone { get; set; }
        public string HandoverStatus { get; set; }
        public Nullable<bool> HandoverDone { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
