//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;

    public partial class WFM_QAScore
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> RfpTorCompliance { get; set; }
        public Nullable<int> MethodologyApproach { get; set; }
        public Nullable<int> KeyExpertsCv { get; set; }
        public Nullable<int> RelevantExperience { get; set; }
        public Nullable<int> WorkPlanDeliverables { get; set; }
        public Nullable<int> MandatoryAttachments { get; set; }
        public Nullable<int> FinancialCompetitiveness { get; set; }
        public Nullable<int> ProposalQuality { get; set; }
        public Nullable<int> FinalQcSubmissionReadiness { get; set; }
        public Nullable<int> Total { get; set; }
        public string Decision { get; set; }
        public string Notes { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
