//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;

    public partial class WFM_BidRecommendation
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ConsortiumJV { get; set; }
        public string Source { get; set; }
        public string StrategicFit { get; set; }
        public Nullable<bool> Eligible { get; set; }
        public Nullable<int> RecommendStatusId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
