//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFM.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFM_Employee
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string FixedLine { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public int DesignationId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual WFM_Designation WFM_Designation { get; set; }
    }
}
